Repository shrebox/Hacktoberfest-2020, pull requests merged in 2020-10, with the labels that each got.

#1 Update README.md
  README.md
Labels: hacktoberfest-accepted

#2 Update README.md
  README.md
Labels: hactoberfest-accepted

#3 Update README.md
  README.md
Labels: hacktoberfest-accepted

#9 Create Ayushi
  Ayushi
Labels: hacktoberfest-accepted

#8 Create ADITI
  ADITI
Labels: hacktoberfest-accepted

#7 Create Ananya
  Ananya
Labels: hacktoberfest-accepted

#17 Added something
  Pasan.txt
  README.md
Labels: hacktoberfest-accepted

#19 greaterno
  greaterno
Labels: hacktoberfest-accepted

#34 Update README.md
  README.md
Labels: hacktoberfest-accepted

#35 Create Soumyadeepta.md
  Soumyadeepta
Labels: hacktoberfest-accepted

#46 Create Chidvilas
  Chidvilas
Labels: good first issue, hacktoberfest-accepted

#43 Added a simple python hello world file that accepts command line argu…
  hello_world_cla.py
Labels: good first issue, hacktoberfest-accepted
